- Readme.md
This PR adds an example of how to eager load Eloquent model relations when resolving a query after the response to issue #6.
> Eager loading example

- Readme.md
There is a missing
use Folklore\GraphQL\Support\Query; 
in the UsersQuery and changed 
User::find($args['id']);
to 
User::where('id' , $args['id'])->get();
because User::find doesn't returns a array(I opened a issue for it).
> Removed errors from the example

- src/Folklore/GraphQL/routes.php
- src/config/config.php
A feature I need so I imagine others will also!
> Added middleware option

- src/Folklore/GraphQL/Support/Type.php
> Fix infinite loop

- Readme.md
https://github.com/Folkloreatelier/laravel-graphql/issues/19
I had to dig around for this :) sorry if I missed the obvious thought this would help
> Bring in some info from ticket to update docs

- Readme.md
fixing issue
https://github.com/Folkloreatelier/laravel-graphql/issues/41
> Fixing custom fields example

- Readme.md
- src/Folklore/GraphQL/Commands/PublishCommand.php
- src/Folklore/GraphQL/Console/PublishCommand.php
- src/Folklore/GraphQL/LumenGraphQLServiceProvider.php
- src/Folklore/GraphQL/lumen_routes.php
I just added lumen support for this package because I want to give this package a try for my lumen application and I have seen the open issue: #23
To test this, you can configure your `composer.json`
```json
...
"repositories": [
{
"type": "vcs",
"url": "https://github.com/fieteboerner/laravel-graphql"
}
],
"require": {
...
"folklore/graphql": "dev-lumen-support"
},
...
```
I would be thankful for any feedback.
> Add Lumen support

- src/Folklore/GraphQL/Console/GraphiQLMakeCommand.php
- src/Folklore/GraphQL/Console/stubs/graphiql.stub
- src/Folklore/GraphQL/Console/stubs/graphiql_routes.stub
- src/Folklore/GraphQL/ServiceProvider.php
For me GraphiQL is one of the best features of GraphQL, so I tought I would share a command to automatically create a blade view and add a /graphiql route to your web.php route file.
I used a CDN for all assets to have no added dependencies to the project.
Thanks!
> Add a command to generate a GraphiQL view and a route at /graphiql

- Readme.md
`GraphQL::type('user')` is undefined, use `GraphQL::type('User')` instead
> update readme typo

- src/Folklore/GraphQL/ServiceProvider.php
- src/config/config.php
- tests/ConfigTest.php
As described in #60.
Sorry for the whitespace changes, my editor auto trim them on save.
> Added config options for security (Query Max Complexity and Max Depth).

- src/Folklore/GraphQL/GraphQLController.php
- src/config/config.php
- tests/EndpointTest.php
Used by apollo-client to send queries in batches.
http://dev.apollodata.com/core/network.html#BatchingExplained
> Feature batched queries

- Readme.md
Just fixed some small bugs in the example code that makes it not work if you copy paste it :)
> Fixed example code mistakes

- Readme.md
- docs/advanced.md
> Adds missing documentation for interfaces and enums

- composer.json
- src/Folklore/GraphQL/ServiceProvider.php
- src/config/config.php
https://gi…thub.com/webonyx/graphql-php/pull/131
> Adds config option for DisableIntrospection security rule 

- docs/advanced.md
Some small, but needed, addition to the Enum section of the documentation. In reference to the discussion on ticket #111.
> Added; more detailed documentation of Enum implementation.

- src/config/config.php
Fixed typo in config.
Also, thank you for making this package 😄
> Fixed typo in config

- docs/troubleshooting.md
I experienced an issue with empty strings getting set to null and debugged it down to a laravel middleware.
It took me 2 hours to figure this out and maybe someone else will stumble upon this.
I also think it wouldn't hurt to have a Q&A/Troubleshooting document in there, because i stumble upon the same questions from time to time and I guess most people are in the beginning.
> Added a troubleshooting document

- src/Folklore/GraphQL/Error/AuthorizationError.php
- src/Folklore/GraphQL/GraphQL.php
- src/Folklore/GraphQL/GraphQLController.php
- src/Folklore/GraphQL/Support/Field.php
With this commit, any `Field` instance can implement an `authorize` method which must return a boolean. If the method returns `false` then an `HTTP 403` will be returned from the controller.
> Implement "authorize" method

- src/resources/views/graphiql.php
> update grphaiql version

- Readme.md
- composer.json
A small change to allow auto-discovery do its magic.
https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518
> Added laravel auto-discovery for service provider and alias

- .gitignore
- src/Folklore/GraphQL/Relay/EdgesCollection.php
- src/Folklore/GraphQL/Relay/Support/ConnectionType.php
- src/Folklore/GraphQL/Relay/Support/Traits/ResolvesFromQueryBuilder.php
- tests/Relay/RelayEdgesCollectionTest.php
- tests/Relay/RelayTest.php
Get count of total items from the query
> add field total to ConnectionType

- src/Folklore/GraphQL/LumenServiceProvider.php
- src/Folklore/GraphQL/Relay/ConnectionEdgeType.php
- src/Folklore/GraphQL/Relay/NodeIdField.php
- src/Folklore/GraphQL/Relay/NodeQuery.php
- src/Folklore/GraphQL/Relay/Relay.php
- src/Folklore/GraphQL/Relay/Support/ConnectionType.php
- src/Folklore/GraphQL/Relay/Support/Traits/TypeIsNode.php
> Removed dependency on Facades

- src/resources/views/graphiql.php
Copied the graphiql.php view file from master
> Updated graphiql view template with latest version from master branch

- composer.json
Replace misprint in composer.json - that  should fix https://github.com/Folkloreatelier/laravel-graphql/issues/221
> Replace misprint in composer.json

- src/Folklore/GraphQL/Support/Traits/ShouldValidate.php
- tests/MutationTest.php
- tests/Objects/ExampleNestedValidationInputObject.php
- tests/Objects/ExampleValidationInputObject.php
- tests/Objects/UpdateExampleMutation.php
- tests/Objects/UpdateExampleMutationWithInputType.php
resolves #234 - see for details
Comments, etc. appreciated.
Tasks:
> Input Object Validation
