composer.json

Updates illuminate support to 5.2, to allow installing into laravel 5.2.

Update for laravel 5.2

---

Readme.md

would then `json_decode` to null.

If I did not wrap the parameter key in quotes it

---

src/Folklore/GraphQL/GraphQL.php

I have no Mutations in my schema, GraphiQL was throwing an issue as there's an empty Mutation type.

Allow Mutations to be optional

---

src/Folklore/GraphQL/LumenServiceProvider.php

Fixes #81
`registerGraphQL` was called twice for some reason. So fast fix it

PHPUnit run fix

---

src/Folklore/GraphQL/Support/Type.php

This PR adds support for using GraphQL enums.
To create a new EnumType: 
class TestEnumType extends GraphQLType
{
protected $enumObject = true;
protected $attributes = [
'values' => [
'YES' => [
'value' => 'YES',
'description' => 'The answer is YES'
],
'NO' => [
'value' => 'NO',
'description' => 'The answer is NO'
]
],
];
}
Add this to your graphql.php type array:
'types' => [TestEnum'=>TestEnumType::class ];
Then use it:
class TestType extends GraphQLType
{
public function fields()
{
return [
'type' => ['type'=>GraphQL::type('TestEnum')]
]
} 
}

Added support for enumtypes.

---

Readme.md

Some whitespaces were written as spaces whilst most else were tabs.
This commit tabifies them.

Cosmetic change: Whitespace fix on README

---

src/Folklore/GraphQL/View/GraphiQLComposer.php
src/config/config.php

Current GraphiQL controller doesn't seem to support specifying the custom schema using `{graphql_schema?}` route parameter.
This PR adds an ability to specify the schema using the URL parameter by appending the same parameter to the query URL.
If you have better idea to improve this solution, please suggest :)
Ref: https://github.com/Folkloreatelier/laravel-graphql/issues/115#issuecomment-302999148

Add custom schema support on GraphiQL

---

docs/advanced.md
src/Folklore/GraphQL/GraphQL.php

According to `config/graphql.php`: 
```
// The name of the input that contain variables when you query the endpoint.
// Most library use "variables", you can change it here in case you need it.
// In previous versions, the default used to be "params"
```
`params` should be `variables`

fix: change `params` to `variables`

---

src/Folklore/GraphQL/View/GraphiQLComposer.php

Due to Lumen not having `router` bound to the container, the view
composer for the GraphiQL tool was not properly setting the graphqlPath.

Fixes GraphiQLComposer for use within Lumen

---

src/Folklore/GraphQL/ServiceProvider.php
tests/GraphQLTest.php

Hi there,
I originally reorganized the service provider while I was optimizing it, but reverted those changes because the diff is too hard to look through. If you like the PR, I would love to reorganize things after it's been approved (sort methods by visibility and dependency).
This PR implements:
- Wait to register types, schemas, event listeners, and security rules until GraphQL is resolved from the container — this means that significantly less `boot()` logic needs to run for requests that don't use GraphQL at all
- Replace helper methods like `config()` with `$this->app['config']`
- Simplify references to classes in the `Folklore\GraphQL` namespace

Optimize service provider

---

.gitignore
src/config/config.php

When I first used this lib, I was quite annoyed that the config file looked a bit messy. I converted the comments to multi-line to make it look much cleaner. I also added the `.idea/` folder that Jetbrains IDE's automatically create to the .gitignore file.

Cleaned up config file and ignored Jetbrains IDE files

---

src/Folklore/GraphQL/LumenServiceProvider.php

Otherwise calling `php artisan` dies with:
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined method Laravel\Lumen\Application::group()
```
Versions:
- PHP 7.1.9
- Lumen 5.5.0
- folklore/graphql 1.0.25

Fix LumenServiceProvider::getRouter()

---

src/Folklore/GraphQL/Support/Field.php
tests/Objects/ExamplesAuthorizeQuery.php

During my usage of `authorize()` I often noticed that I needed the `$args`.
Example: Users can edit their own profile, but not that of others. In an `updateProfile` mutatation, I want to check if the supplied `id` argument matches the ID of the user who initiated the mutation. The `authorize` method is where stuff like this is supposed to happen, so I need `$args` there.

Updated Field to include $args in the authorize method

---

src/Folklore/GraphQL/Support/Field.php
tests/Objects/ExamplesAuthorizeQuery.php

Fixes a missing argument for the authorize method. Introduced in #199.
This is a BC to the api so you might want to release as a minor update perhaps. Your call.

Add missing argument to authorize method

---

src/Folklore/GraphQL/GraphQLController.php
src/config/config.php

Added a feature to apply middleware per schema.
```php
/**
* Any middleware for a specific 'graphql' schema
*/
'middleware_schema' => [
'default' => ['auth.basic'],
],
```
Possible solution for #191

Added per schema middleware

---

Readme.md

Hi there!
The package **readme** does not comply with Laravel code standard.
I changed tabs to spaces, and the PHP snippets to PSR-2, making the readme more pleasant to read.
Hope it helps.
Best regards,
Rafael Pacheco.

Readme fixes with tabs to space and PHP to PSR-2

---

src/Folklore/GraphQL/Console/EnumMakeCommand.php
src/Folklore/GraphQL/Console/FieldMakeCommand.php
src/Folklore/GraphQL/Console/InterfaceMakeCommand.php
src/Folklore/GraphQL/Console/ScalarMakeCommand.php
src/Folklore/GraphQL/ServiceProvider.php

This registers the newly added `Enum`/`Field`/`Interface`/`Scalar` type make commands to the artisan command lists like existing `TypeMakeCommand`.

Register additional type make commands as artisan commands

---

src/Folklore/GraphQL/Support/Type.php

I encountered a situation where I wanted to use a field multiple times but resolve a different data set for each instance. This does not break any existing functionality, it merely adds more flexibility.
```php
'user' => UserField::class, // Resolves itself
'language_from' => [
'class' => LanguageField::class,
'resolve' => function ($root, $args) {
return $root->translatableFrom;
}
],
'language_to' => [
'class' => LanguageField::class,
'resolve' => function ($root, $args) {
return $root->translatableTo;
}
],
```

Allowing field to be specified as a class combining with a resolver

---

src/Folklore/GraphQL/ServiceProvider.php
src/config/config.php

We have a need to be able to override the GraphiQLComposer. Made the following changes:
1. Added a new config parameter called 'composer' under the 'graphql.graphiql' section of config.
2. Updated the ServiceProvider to read the config or fall back to the default if config value doesn't exist.

Allows GraphiQLComposer to be overridden in config

---

src/Folklore/GraphQL/GraphQLController.php

Using the default setup, graphiql routes were given the default middleware - which is not expected. This PR does a check on the route to make sure we are not hitting the controller for graphiql.

Ensuring graphiql does not get the schema middleware

---

src/Folklore/GraphQL/GraphQLController.php
src/Folklore/GraphQL/View/GraphiQLComposer.php

Better Lumen support,
It seems the `Request->route()` returns an array and not an instance of \Illuminate\Routing\Route.
[See this issue (fixed in future release of Lumen)](https://github.com/laravel/lumen-framework/issues/119)
Also specified in [documentation](https://laravel.com/api/5.5/Illuminate/Http/Request.html#method_route)
Middlewares of graphql and its schemas are applied to GraphiQL routes, but that's not what we expect.

Route can be an array instead of object

---

src/Folklore/GraphQL/GraphQL.php

Fixes #198 
As mentioned by @leehicks in the issue #198 there is a bug preventing us from using separate types per schema.
```php
'schemas' => [
'default' => [
'query' => [
'TestQuery' => \App\GraphQL\Query\TestQuery::class,
],
'mutation' => [
],
'types' => [
'TestType' => \App\GraphQL\Type\TestType::class,
],
]
],
```

Fixes issue #198 - different types per schema

---

src/Folklore/GraphQL/Console/stubs/scalar.stub
src/Folklore/GraphQL/GraphQL.php
src/Folklore/GraphQL/Support/Contracts/TypeConvertible.php
src/Folklore/GraphQL/Support/Type.php

This is an attempt at resolving #137. 
I believe to define and use a custom scalar within the config files `types` section, all that we need to do is ensure that the scalar implements a `toType` function. Generally, that function is just constructing the class, but I tried to leave that up to the developer.
Defining the interface also allows for smarter checking during construction of the schema and better error handling. 
Let me know what you think.

Define custom scalars with an interface

---

src/Folklore/GraphQL/GraphQLController.php

See when using custom prefix in `config.php` `middleware_schema` will only work for `default` schema! other schemas will fails to run. This should rectify the issue.

fix custom prefix bug

---

src/Folklore/GraphQL/Support/Traits/ShouldValidate.php
tests/MutationTest.php
tests/Objects/UpdateExampleMutationWithInputType.php

Fixed missing arguments in the ``validationErrorMessages`` method. #261 
We can have more control to compute the validation messages.
For example :
```php
public function validationErrorMessages($root, $args, $context)
{
$inavlidEmail = array_get($args, 'test_with_rules_input_object.nest.email');
return [
'test.required' => 'A test is required.',
'test_with_rules_input_object.nest.email.email' => 'Invalid your email : '.$inavlidEmail,
];
}
```
@dmongeau  Thank you !

Customizing the validation error messages and fixed arguments

---

src/Folklore/GraphQL/Support/Traits/ShouldValidate.php

The same as you can use the `withValidator` method on form requests, we can now do that with mutations.
From the Laravel docs on this method on form requests:
> If you would like to add an "after" hook to a form request, you may use the withValidator method. This method receives the fully constructed validator, allowing you to call any of its methods before the validation rules are actually evaluated:
```php
/**
* Configure the validator instance.
*
* @param  \Illuminate\Validation\Validator  $validator
* @return void
*/
public function withValidator($validator)
{
$validator->after(function ($validator) {
if ($this->somethingElseIsInvalid()) {
$validator->errors()->add('field', 'Something is wrong with this field!');
}
});
}
```
Additionally we're also passing through the `$args` as the …

Add hook for validator before resolution

---

src/Folklore/GraphQL/GraphQL.php
src/config/config.php
tests/ConfigTest.php
tests/EndpointTest.php
tests/GraphQLQueryTest.php
tests/GraphQLTest.php
tests/TestCase.php

webonyx/graphql-php uses the new GraphQL\Type\Schema and not the old one.
Especially useful when using BuildSchema to build a schema, which builds the schema using the new class.

Deprecated: `GraphQL\Schema` moved to `GraphQL\Type\Schema`

---

src/Folklore/GraphQL/GraphQL.php
src/config/config.php
tests/ConfigTest.php
tests/EndpointTest.php
tests/GraphQLQueryTest.php
tests/GraphQLTest.php
tests/Objects/queries.php
tests/TestCase.php

Custom resolvers are needed if Schema is build using \GraphQL\Utils::BuildSchema.
This would make the shorthand example usable, see https://github.com/webonyx/graphql-php/tree/master/examples/02-shorthand

Added custom resolver feature

---

composer.json

Simple change to add Laravel 5.6 as a supported option.

Update for Laravel 5.6

---

src/resources/views/graphiql.php

Updates version. This updated version supports markdown on the description of the fields.

Update graphiql to latest version

---

src/Folklore/GraphQL/GraphQL.php
src/config/config.php

Currently executeAndReturnResult() will be used to execute the query. But it's deprecated. The new one is executeQuery and it supports overriding the defaultFieldResolver too.

Add defaultFieldResolver feature with new executeQuery call

---

src/Folklore/GraphQL/Support/Field.php
tests/GraphQLQueryTest.php
tests/Objects/ExamplesAuthenticatedQuery.php
tests/Objects/queries.php
tests/TestCase.php

Currently we can authenticate with middleware where we have different schema for guest and authenticated user. This works fine but its better to have this control in each query or mutation and having one schema.
For example lets say we have a query where we want current user info and latest 5 post in one query.
`post` query is public and `me` requires authentication.  
```
query currentUserAndPublicPosts {
me {
id
name
email
}
post(first: 5) {
name
category
createdAt
}
}
``` 
I do not see the above query working by having multiple schema of guest and authenticated user.
With this PR we will be able to check authentication per query or mutation by adding following to the query or mutation.
```php
public function authenticated($root, $args, $currentUser)
{
return $currentUser && …
```

authenticate per query or mutation instead of middleware

---

src/Folklore/GraphQL/GraphQL.php
src/Folklore/GraphQL/Support/PaginationCursorType.php
src/Folklore/GraphQL/Support/PaginationType.php
tests/Objects/ExamplesPaginationQuery.php
tests/Objects/queries.php
tests/PaginationTest.php
tests/TestCase.php

Created a new implementation of my previous pagination PR (#242).
Example project: https://github.com/kevinvdburgt/laravel-graphql-example/blob/62daca1f6ebe5664afc01488a5b437ab7b6f32bf/app/GraphQL/Query/PostsQuery.php#L20
When using the pagination type, for example:
```php
public function type()
{
return GraphQL::pagination(GraphQL::type('Post'));
}
```
The library will create's a type `PostPagination` and a `PaginationCursor` type when it doesnt exists yet.

Added pagination with cursor info

---

composer.json

Changed `type` is `project` to `library`.

chore: Correct setting composer package type
